version: '3.7'

services:
  
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=example
     - POSTGRES_DB=backend_db
    container_name: backend_db
    volumes:
     - ./data/postgres_database:/var/lib/postgresql/data
  
  lautapeli-app:
    build: .
    command: npm run dev
    environment:
      - PORT=3001
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=example
      - POSTGRES_DATABASE=backend_db
      - POSTGRES_USE_SSL="false"
      - NODE_ENV=development
    ports:
      - 3001:3001
    volumes:
      - ./:/usr/src/app # Let us modify the contents of the container locally
      - node_modules:/usr/src/app/node_modules # A bit of node magic, this ensures the dependencies built for the image are not available locally.
    container_name: lautapeli-app-dev
    depends_on: [db]
  

volumes: # This is required for the node_modules named volume
  node_modules:
