version: '3.7'

services:
  
  test-db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test_db
    container_name: test_db
    volumes:
     - ./data/postgres_test_database:/var/lib/postgresql/data
  
  node-test-env:
    image: backend_lautapeli-app:latest
    command: npm run wait_test
    environment:
      - PORT=3001
      - POSTGRES_HOST=test_db
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DATABASE=test_db
      - POSTGRES_USE_SSL="false"
      - SECRET=kaalikääryle
      - ADMIN_USER=perunalaatikko
      - ADMIN_PASSWORD=vihreakuula
      - NODE_ENV=test
    ports:
      - 3002:3001
    volumes:
      - ./:/usr/src/app # Let us modify the contents of the container locally
      - node_modules:/usr/src/app/node_modules # A bit of node magic, this ensures the dependencies built for the image are not available locally.
    container_name: node-test-env
    depends_on: [test-db]
  

volumes: # This is required for the node_modules named volume
  node_modules:
